baseURL = 'https://notshared.org/'
locale = 'en-us'
title = 'Not Shared'
theme = "github.com/imfing/hextra"
defaultContentLanguage = 'en'

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"

[privacy]
[privacy.disqus]
disable = true
[privacy.googleAnalytics]
disable = true
respectDoNotTrack = true
[privacy.instagram]
disable = true
simple = true
[privacy.vimeo]
disable = true
enableDNT = true
simple = true
[privacy.x]
disable = true
enableDNT = true
simple = true
[privacy.youTube]
disable = true
privacyEnhanced = true
