# Main
[[ main ]]
identifier = "guides"
name = "Privacy Guides"
pageRef = "/guides"
weight = 1

[[ main ]]
identifier = "reports"
name = "Reports"
pageRef = "/reports"
weight = 2

[[ main ]]
identifier = "gallery"
name = "Gallery"
pageRef = "/gallery"
weight = 3
[[ main ]]
identifier = "gallery-posters"
parent = "gallery"
name = "Posters"
pageRef = "/gallery/posters"
weight = 1
[[ main ]]
identifier = "gallery-stickers"
parent = "gallery"
name = "Stickers"
pageRef = "/gallery/stickers"
weight = 2

[[ main ]]
name = "Search"
weight = 10
params.type = "search"

[[ main ]]
name = "Theme"
params.type = "theme-toggle"
weight = 20

[[ main ]]
name = "Language"
params.type = "language-switch"
params.label = true
weight = 21

[[ main ]]
identifier = "about"
name = "About"
pageRef = "/about"
weight = 30
